ssh:
  image: yfix/ssh
  container_name: yfix_test_ssh
  restart: always
  privileged: true
  ports:
    - "30122:22"
  volumes:
    - ./container-files/config/authorized_keys:/config/authorized_keys:ro
    - ./container-files/etc/supervisor/conf.d/sshd.conf:/etc/supervisor/conf.d/sshd.conf
    - ./container-files/var/log/supervisor:/var/log/supervisor
