version: '2'
services:
  ssh:
    build: .
#    image: yfix/ssh
    restart: always
    privileged: true
    ports:
      - "30122:22"
    volumes:
      - ./docker/config/authorized_keys:/config/authorized_keys:ro
      - ./docker/etc/supervisor/conf.d/sshd.conf:/etc/supervisor/conf.d/sshd.conf
      - ./docker/var/log/supervisor:/var/log/supervisor
